import { Quicksand } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";

/**
 * description :- {fonts}
 * created_at:- 01/01/2024 11:27:16
 */
const quicksand = Quicksand({ subsets: ["latin"], weight: ["300", "400"] });

/**
 * description :- {meta}
 * created_at:- 01/01/2024 12:45:36
 */
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

/**
 * description :- RootLayout
 * created_at:- 01/01/2024 11:27:30
 */
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={quicksand.className}>{children}</body>
        </html>
    );
}
